### PR TITLE
Enabled mouse scrolling and disabled downsampling of thumbnails

### PR DESCRIPTION
**Pull request by mrMoe**
greetings
moe

### CODE REVIEW

**Comment by jeromerobert** [comment]
Your patch contains too much noise so it cannot be read. Please let your commit contains only the changes you describes in the commit description (no white space or reindent changes).

**Comment by mrMoe** [comment]
should I break the pull Request into three for 
Disabling downsampling,
Enabled mouse scrolling,
Rreduced newlines and Corrected indentation
?

**Comment by jeromerobert** [comment]
Yes that would be better. Please don't do changes in new lines or indentations, because I want this repo to stay as close as possible as https://gna.org/projects/pdfshuffler/. Let Konstantinos Poulios (the original author) manage the source code format.

**Comment by jeromerobert** [comment]
I'm back again on that PR. Those features are nice but I'm really unable to find the actual changes in the commit as they are too noisy. As it now quite old I close it. May you find time and energy to make it more readable.

**Pull request closed without merging**
